### ISSUE TITLE
Add documentation on how to configure this for SSL Kafka clusters

### ISSUE THREAD

**Issue by bikassaha** [hortonworks-spark/skc#1]
May need a code example too, in case the configs are not transparently passed into Kafka libs from the app config.

**Comment by jerryshao** [comment]
I will open a JIRA to track this.

**Comment by jerryshao** [comment]
Fixed, also verified in SSL Kafka clusters.

**Comment by jerryshao** [comment]
@bikassaha please see the commit (https://github.com/hortonworks-spark/skc/commit/4d7dbdb6d8b4cbdb38668e0742622f553dea66ff).
